staticmanUrl: https://anasbasem.herokuapp.com/v2/entry/basemwahba/isitfinal/master/comments
enableComments: true

reCaptcha:
  siteKey: "6Lc_JOAUAAAAAKJbpIVumbpgj1q0I86C-E5KzqBR"
  secret: "WMc592PoF6eC4WJjDCTGyzGIal3H41ha1epdVOmfT6m1X6zdagnsh/yQpJFgsr9IgUraucZay+aDkWQrqTSDnnl0RxIV0XBQu5oamMvJ4PA5mU9P9g7v7H7Ko/uXVG66ujylgBjiMKdy7ImcNKweh7S4X1x9613QW9pZFvrvCMoE84OtB0W/WuAMhOMlrvM/faZHak6I11nVZtbKddaCP7dgUbaF0xmQOtIr91xiLpfA74Dw5nZbmoNQ4rJWqy5QWeR2ZexfmEs3jhS58C3JiAK4Vpv0FgEdPpB6CO4sC9xVJrm1qYLuPyiubfHM0k8Rc81ZfzGLNrowpCAlMRJNqA=="
